global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-sophos-outboundproxy
  regions:
    - us-east-1
  reporting: true

tests:
  quickstart-sophos-outboundproxyt1:
    parameter_input: sophos-outbound-proxy-params.json
    template_file: sophos.template

